// Generated by CoffeeScript 1.7.1
(function() {
  var $, chunks, fs, http, iconv, regs, size, url;

  http = require('http');

  fs = require('fs');

  $ = require('cheerio');

  iconv = require('iconv-lite');

  url = 'http://www.qq.com';

  chunks = [];

  size = 0;

  regs = {
    http: /http|\/\//
  };

  http.get(url, function(res) {
    res.on('data', function(chunk) {
      chunks.push(chunk);
      return size += chunk.length;
    });
    return res.on('end', function() {
      var $html, $links, data, html, links, result;
      links = {};
      data = Buffer.concat(chunks, size);
      html = iconv.decode(data, 'gbk');
      $html = $.load(html);
      $links = $html('a[href]');
      result = '';
      $links.each(function(i, ele) {
        var href, txt;
        href = $(ele).attr('href');
        txt = $(ele).text().replace(/\s|\t|\n/g, '');
        if (regs.http.test(href)) {
          return result += txt + ':' + href + '\n';
        }
      });
      return fs.writeFile(__dirname + '/links.txt', result);
    });
  });

}).call(this);
